version: '2'

services:
  ######################################################################################################################
  ##################################################      Ocelot      ##################################################
  ######################################################################################################################
  agent:
    image: inspectit/inspectit-ocelot-agent:1.11.1
    container_name: agent
    mem_limit: 128M
    volumes:
      - agent-vol:/agent

  ocelot-config-server:
    image: inspectit/inspectit-ocelot-configurationserver:1.11.1
    container_name: ocelot-config-server
    mem_limit: 256M
    environment:
      - INSPECTIT_CONFIG_SERVER_WORKING_DIRECTORY=/configuration-server
      - INSPECTIT_CONFIG_SERVER_DEFAULT_USER_PASSWORD=demo
    volumes:
      - ./configuration-server:/configuration-server
    ports:
      - 8090:8090

  ######################################################################################################################
  ##################################################      Jaeger      ##################################################
  ######################################################################################################################
  jaeger:
    image: jaegertracing/all-in-one:1.6
    container_name: jaeger
    ports:
      - 16686:16686

  ######################################################################################################################
  ##################################################    Petclinic     ##################################################
  ######################################################################################################################
  config-server:
    image: springcommunity/spring-petclinic-config-server
    container_name: config-server
    environment:
      - INSPECTIT_SERVICE_NAME=config-server
      - INSPECTIT_CONFIG_HTTP_URL=http://ocelot-config-server:8090/api/v1/agent/configuration
      - INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_ENABLED=false
      - INSPECTIT_EXPORTERS_METRICS_INFLUX_URL=http://influxdb:8086
      - INSPECTIT_EXPORTERS_TRACING_JAEGER_URL=http://jaeger:14268/api/traces
    mem_limit: 512M
    depends_on:
      - agent
      - ocelot-config-server
    ports:
     - 8888:8888

  discovery-server:
    image: springcommunity/spring-petclinic-discovery-server
    container_name: discovery-server
    environment:
      - INSPECTIT_SERVICE_NAME=discovery-server
      - INSPECTIT_CONFIG_HTTP_URL=http://ocelot-config-server:8090/api/v1/agent/configuration
      - INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_ENABLED=false
      - INSPECTIT_EXPORTERS_METRICS_INFLUX_URL=http://influxdb:8086
      - INSPECTIT_EXPORTERS_TRACING_JAEGER_URL=http://jaeger:14268/api/traces
    mem_limit: 512M
    depends_on:
      - agent
      - ocelot-config-server
      - config-server
    entrypoint: ["./dockerize","-wait=tcp://config-server:8888","-timeout=60s","--","java", "-javaagent:/agent/inspectit-ocelot-agent.jar", "org.springframework.boot.loader.JarLauncher"]
    volumes:
      - agent-vol:/agent
    ports:
     - 8761:8761

  customers-service:
    image: springcommunity/spring-petclinic-customers-service
    container_name: customers-service
    environment:
      - INSPECTIT_SERVICE_NAME=customers-service
      - INSPECTIT_CONFIG_HTTP_URL=http://ocelot-config-server:8090/api/v1/agent/configuration
      - INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_ENABLED=false
      - INSPECTIT_EXPORTERS_METRICS_INFLUX_URL=http://influxdb:8086
      - INSPECTIT_EXPORTERS_TRACING_JAEGER_URL=http://jaeger:14268/api/traces
    mem_limit: 512M
    depends_on:
      - agent
      - ocelot-config-server
      - config-server
      - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-javaagent:/agent/inspectit-ocelot-agent.jar", "org.springframework.boot.loader.JarLauncher"]
    volumes:
      - agent-vol:/agent
    ports:
      - 8081:8081

  visits-service:
    image: springcommunity/spring-petclinic-visits-service
    container_name: visits-service
    environment:
      - INSPECTIT_SERVICE_NAME=visits-service
      - INSPECTIT_CONFIG_HTTP_URL=http://ocelot-config-server:8090/api/v1/agent/configuration
      - INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_ENABLED=false
      - INSPECTIT_EXPORTERS_METRICS_INFLUX_URL=http://influxdb:8086
      - INSPECTIT_EXPORTERS_TRACING_JAEGER_URL=http://jaeger:14268/api/traces
    mem_limit: 512M
    depends_on:
     - agent
     - ocelot-config-server
     - config-server
     - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-javaagent:/agent/inspectit-ocelot-agent.jar", "org.springframework.boot.loader.JarLauncher"]
    volumes:
      - agent-vol:/agent
    ports:
     - 8082:8082

  vets-service:
    image: springcommunity/spring-petclinic-vets-service
    container_name: vets-service
    environment:
      - INSPECTIT_SERVICE_NAME=vets-service
      - INSPECTIT_CONFIG_HTTP_URL=http://ocelot-config-server:8090/api/v1/agent/configuration
      - INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_ENABLED=false
      - INSPECTIT_EXPORTERS_METRICS_INFLUX_URL=http://influxdb:8086
      - INSPECTIT_EXPORTERS_TRACING_JAEGER_URL=http://jaeger:14268/api/traces
    mem_limit: 512M
    depends_on:
     - agent
     - ocelot-config-server
     - config-server
     - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-javaagent:/agent/inspectit-ocelot-agent.jar", "org.springframework.boot.loader.JarLauncher"]
    volumes:
      - agent-vol:/agent
    ports:
     - 8083:8083

  api-gateway:
    image: springcommunity/spring-petclinic-api-gateway
    container_name: api-gateway
    environment:
      - INSPECTIT_SERVICE_NAME=api-gateway
      - INSPECTIT_CONFIG_HTTP_URL=http://ocelot-config-server:8090/api/v1/agent/configuration
      - INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_ENABLED=false
      - INSPECTIT_EXPORTERS_METRICS_INFLUX_URL=http://influxdb:8086
      - INSPECTIT_EXPORTERS_TRACING_JAEGER_URL=http://jaeger:14268/api/traces
    mem_limit: 512M
    depends_on:
      - agent
      - ocelot-config-server
      - config-server
      - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-javaagent:/agent/inspectit-ocelot-agent.jar", "org.springframework.boot.loader.JarLauncher"]
    volumes:
      - agent-vol:/agent
    ports:
     - 8080:8080

  tracing-server:
    image: openzipkin/zipkin
    container_name: tracing-server
    mem_limit: 512M
    environment:
    - JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -Djava.security.egd=file:/dev/./urandom
    ports:
     - 9411:9411

  admin-server:
    image: springcommunity/spring-petclinic-admin-server
    container_name: admin-server
    mem_limit: 512M
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 9090:9090


  ######################################################################################################################
  ##################################################    InfluxDB      ##################################################
  ######################################################################################################################

  influxdb:
    image: influxdb:1.7.1
    container_name: influxdb
    environment:
      - INFLUXDB_HTTP_FLUX_ENABLED=true
      - INFLUXDB_HTTP_LOG_ENABLED=false
      - INFLUXDB_DATA_QUERY_LOG_ENABLED=false
    mem_limit: 512M
    volumes:
      - ./influx:/docker-entrypoint-initdb.d
    ports:
      - 8086:8086

  ######################################################################################################################
  ##################################################     Grafana      ##################################################
  ######################################################################################################################

  grafana:
    image: inspectit/grafana:servicegraph-v2.1
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=demo
      - GF_PATHS_PROVISIONING=/usr/share/grafana/custom/
    volumes:
      - ./grafana/provisioning/influxdb:/usr/share/grafana/custom/
    # - ./grafana/provisioning/influxdb:/usr/share/grafana/data\plugins
    ports:
      - 3001:3000


volumes:
  agent-vol:
